#define AimChangeAccuracyRecoveryTimeMS 0
#define AimChangeModifier 1
#define AimChangeSensitivity 2
#define AimSpreadMax 3
#define AimSpreadMin 4
#define AirSupply 5
#define AirSupplyDepletionRate 6
#define AirSupplyRegenRate 7
#define AirSupplyRegenTickInterval 8
#define AirSupplyDepletionTickInterval 9
#define AirSupplyDamageRate 10
#define AirSupplyDamageInterval 11
#define FallDamageMod 12
#define FallDamageLethalHeight 13
#define FallDamageStartHeight 14
#define BleedingOutHealth 15
#define BleedingOutHealthDegenRate 16
#define BleedingOutHealthDegenTickInterval 17
#define BleedingOutDieQuickMultiplier 18
#define BleedingOutReviveHealthPercentage 19
#define ClipSize 20
#define CoverAimSpreadMax 21
#define CoverAimSpreadMin 22
#define CoverSpreadMax 23
#define CoverSpreadMin 24
#define CriticalHitChanceResilience 25
#define DamageDoneToSuppressedTargetMod 26
#define DamageDoneToElitesMod 27
#define DamageMultiplierArms 28
#define DamageMultiplierBody 29
#define DamageMultiplierHead 30
#define DamageMultiplierLegs 31
#define DamageTakenMod 32
#define DamageTakenFromElitesMod 33
#define DownedDamageMax 34
#define DownedDamageMaxPVP 35
#define DownedDamageMod 36
#define DownedDamageModPVP 37
#define DownedHealth 38
#define DownedHealthDegenRate 39
#define DownedHealthDegenTickInterval 40
#define DownedInARowMax 41
#define DownedInARowMaxTimePeriod 42
#define DownedDieQuickMultiplier 43
#define DownedReviveHealthPercentage 44
#define TalentDownedAssistSpeedMod 45
#define TalentSecondChanceHealMod 46
#define TalentSecondChanceCooldown 47
#define Health 48
#define HealthRegenDelay 49
#define HealthRegenExitCombatDelay 50
#define HealthRegenRate 51
#define HealthRegenTickInterval 52
#define HealthSegments 53
#define HorizontalRecoilBorderLeft 54
#define HorizontalRecoilBorderRight 55
#define HorizontalRecoilLeft 56
#define HorizontalRecoilRecoveryTimeMS 57
#define HorizontalRecoilRight 58
#define HorizontalRecoilTimeMS 59
#define IncomingHealingMod 60
#define OutgoingHealingMod 61
#define DarkZoneInventory 62
#define DefaultInventory 63
#define ResourceInventory 64
#define VanityInventory 65
#define BackupSpaceInventory 66
#define StashInventory 67
#define DarkZoneStashInventory 68
#define MailboxInventory 69
#define LifeOnKill 70
#define LootChanceMod 71
#define LootedAmmoMod 72
#define LootedGoldMod 73
#define LootMagicFind 74
#define MeleeDamagePvP 75
#define MeleeDamage 76
#define MeleeDamageMitigationPercentage 77
#define MovementSpeedMod 78
#define PitchRecoveryPerSecond 79
#define PitchRecoveryPercent 80
#define PulseCriticalHitChance 81
#define PulseCriticalHitDamage 82
#define PVPDamageModifier 83
#define RPM 84
#define RangeLong 85
#define RangeMax 86
#define RangeOptimal 87
#define RecoilBase 88
#define RecoilClimbTimeMS 89
#define RecoilIncreasePerBullet 90
#define RecoilMax 91
#define RecoilMin 92
#define RecoilRecoveryPerSecond 93
#define RecoilRecoveryTimeMS 94
#define RecoilResetTimeMS 95
#define ReloadTimeMS 96
#define EmptyClipFirstRoundReloadTimeMS 97
#define InitialShellReloadTimeMS 98
#define RespawnTimeMS 99
#define RespawnMinimumTime 100
#define ReviveDurationMS 101
#define ReviveFromDeadDurationMS 102
#define ReviveImmunityDuration 103
#define ReviveImmunityRange 104
#define ReviveServerNotifyTickIntervalMS 105
#define SafetyBeltCooldown 106
#define SkillCriticalHitChance 107
#define SkillCriticalHitDamageMod 108
#define SkillHasteMod 109
#define SpreadIncreaseSpeed 110
#define SpreadIncreaseTimeMS 111
#define SpreadMax 112
#define SpreadMin 113
#define SpreadMovementMod 114
#define SpreadReductionSpeed 115
#define StaggerDamageModifier 116
#define StaminaConsumptionRate 117
#define StaminaConsumptionTickInterval 118
#define StaminaDamageTakenMod 119
#define Stamina 120
#define StaminaRegenDelay 121
#define StaminaRegenRate 122
#define StaminaRegenTickInterval 123
#define Suppression 124
#define TargetOutOfCoverDamageMod 125
#define ThrowRangeMod 126
#define TimeToMaxAccuracyMS 127
#define TimeToMinAccuracyMS 128
#define WeaponCriticalHitChance 129
#define WeaponCriticalHitDamageMod 130
#define WeaponCriticalHitChanceVsOOC 131
#define WeaponDrawSpeedMod 132
#define WeaponHolsterSpeedMod 133
#define XPMod 134
#define YawRecoveryPerSecond 135
#define YawRecoveryPercent 136
#define ZoneDiscoveryXP 137
#define PhysicalDamageMin 138
#define PhysicalDamageMax 139
#define PhysicalDamageVariation 140
#define BlastDamageMin 141
#define BlastDamageMax 142
#define BlastDamageVariation 143
#define BleedDamageMin 144
#define BleedDamageMax 145
#define BleedDamageVariation 146
#define BurnDamageMin 147
#define BurnDamageMax 148
#define BurnDamageVariation 149
#define ToxinDamageMin 150
#define ToxinDamageMax 151
#define ToxinDamageVariation 152
#define ElectricDamageMin 153
#define ElectricDamageMax 154
#define ElectricDamageVariation 155
#define NeutralDamageMin 156
#define NeutralDamageMax 157
#define NeutralDamageVariation 158
#define EMPDamageMin 159
#define EMPDamageMax 160
#define EMPDamageVariation 161
#define StaminaDamageMin 162
#define StaminaDamageMax 163
#define StaminaDamageVariation 164
#define TestDamageScaling 165
#define PrimaryOffensiveCalc 166
#define WeaponDamageModBonus 167
#define WeaponTypeDamageModCalc 168
#define NPCArmor 169
#define NPCArmorBypassRatioHead 170
#define NPCArmorBypassRatioBody 171
#define NPCArmorDamageModifier 172
#define NPCArmorBypassModifier 173
#define PhysicalDamageMitigationPercentage 174
#define BlastDamageMitigationPercentage 175
#define BleedDamageMitigationPercentage 176
#define BurnDamageMitigationPercentage 177
#define ToxinDamageMitigationPercentage 178
#define ElectricDamageMitigationPercentage 179
#define NeutralDamageMitigationPercentage 180
#define EMPDamageMitigationPercentage 181
#define StaminaDamageMitigationPercentage 182
#define SelfSourceDamageMitigationPercentage 183
#define FriendlySourceDamageMitigationPercentage 184
#define NPCSourceDamageMitigationPercentage 185
#define OpponentSourceDamageMitigationPercentage 186
#define NullSourceDamageMitigationPercentage 187
#define WeaponMethodDamageMitigationPercentage 188
#define TrapMethodDamageMitigationPercentage 189
#define SkillMethodDamageMitigationPercentage 190
#define StatusEffectMethodDamageMitigationPercentage 191
#define MeleeMethodDamageMitigationPercentage 192
#define EnvironmentMethodDamageMitigationPercentage 193
#define BleedingStatusResistancePercentage 194
#define BlindDeafStatusResistancePercentage 195
#define BurningStatusResistancePercentage 196
#define ConfusedStatusResistancePercentage 197
#define DisruptedStatusResistancePercentage 198
#define ShockedStatusResistancePercentage 199
#define StaggeredStatusResistancePercentage 200
#define SuppressedStatusResistancePercentage 201
#define AimSwayMinHorizontal 202
#define AimSwayMaxHorizontal 203
#define AimSwayMinVertical 204
#define AimSwayMaxVertical 205
#define AimSwaySpeedModifier 206
#define VisualDetectionMod 207
#define VisualStealthMod 208
#define AudialDetectionMod 209
#define AudialStealthMod 210
#define DarkZoneItemsToDrop 211
#define DarkZoneItemsToDropRogue 212
#define DarkZoneConvertXPMod 213
#define DarkZoneXPMod 214
#define DarkZoneXPLossMod 215
#define DarkZoneXPLossRogueMod 216
#define DarkZoneXPLoss 217
#define DarkZoneXPLossRogue 218
#define ThreatPerBullet 219
#define ThreatTotalGeneratedMod 220
#define SuppressionTriggerScore 221
#define SuppressionDefenseModifier 222
#define SuppressionDepletionRate 223
#define SuppressionDuration 224
#define SuppressionBufferScore 225
#define SuppressionBufferResetTime 226
#define StaggerGauge 227
#define StaggerAnimationDurationMod 228
#define ChanceOfGreenToBlueWhenCrafting 229
#define ChanceOfBlueToPurpleWhenCrafting 230
#define ChanceOfPurpleToOrangeWhenCrafting 231
#define XPRepeatableEventsMod 232
#define CreditsRepeatableEventsMod 233
#define SecurityRepeatableEventsMod 234
#define PersonnelRescueMissionsMod 235
#define SupplyDropMissionsMod 236
#define XPHeadshotKillsMod 237
#define XPTacticalKillsMod 238
#define XPSpecialKillsMod 239
#define XPEliteKillsMod 240
#define XPMultiKillsMod 241
#define XPKillsMod 242
#define XPAccoladeMod 243
#define ExtractionTimeMod 244
#define CraftingCostMod 245
#define SkillXPMod 246
#define DZRewardedCredsMod 247
#define VendorCostMod 248
#define AmmoDroppedMod 249
#define CreditsDroppedMod 250
#define LootedCreditsMod 251
#define LootedDZCreditsMod 252
#define UnlockedSkillSlots 253
#define SecondaryWeaponAllowedBool 254
#define RewardedCredsMod 255
#define PerkAutoDiscover 256
#define LastBulletDamageMod 257
#define PrimaryDefensive 258
#define PrimaryOffensive 259
#define PrimarySupport 260
#define OverHeal 261
#define OverHealDepletionDelay 262
#define OverHealDepletionRate 263
#define SignatureSkillResourceRewardMod 264
#define CombatBuff_Cooldown_ 265
#define DefenceBuff_Cooldown_ 266
#define GroupHeal_Cooldown_ 267
#define ModSocketAttributeBonus 268
#define ArmorMitigationDefaultRatingFlatBonus 269
#define ContaminationZoneGasMaskLevelDefaultFlatBonus 270
#define DefaultInventoryFlatBonus 271
#define WeaponDamageBaseModBonus 272
#define PrimaryOffensiveFlatBonus 273
#define PrimaryDefensiveFlatBonus 274
#define PrimarySupportFlatBonus 275
#define AmmoIncendiary 276
#define AmmoExplosive 277
#define ApplyStatusBurnPercentage 278
#define ApplyExplosionConsumablePercentage 279
#define ArmorRatingUI 280
#define DefaultInventoryUI 281
#define ContaminationProtectionUI 282
#define WeaponDamageCompareUI 283
#define WeaponRPMCompareUI 284
#define WeaponMagazineCompareUI 285
#define WeaponAccuracyCompareUI 286
#define WeaponRangeCompareUI 287
#define WeaponReloadTimeCompareUI 288
#define WeaponStabilityCompareUI 289
#define AtributeIndexMax 290